// constants/countries.js
export const COUNTRIES = [
  {
    id: 'za',
    name: 'South Africa',
    code: 'ZA',
    tagline: 'The Rainbow Nation',
    available: true,
    guestAccessible: true,
    cultures: [
      {
        id: 'zulu',
        name: 'Zulu',
        aka: 'amaZulu',
        symbol: '🛡️',
        image: 'Zulu.jpg',
      },
      {
        id: 'xitsonga',
        name: 'Xitsonga',
        aka: 'vaTsonga',
        symbol: '🎵',
        image: 'Xitsonga.jpg',
      },
      {
        id: 'venda',
        name: 'Venda',
        aka: 'vhaVenda',
        symbol: '🐘',
        image: 'Venda.jpg',
      },
      {
        id: 'sotho',
        name: 'Sotho',
        aka: 'Basotho',
        symbol: '🏔️',
        image: 'Sotho.jpg',
      },
      {
        id: 'setswana',
        name: 'Setswana',
        aka: 'Batswana',
        symbol: '🌾',
        image: 'Setswana.jpg',
      },
      {
        id: 'ndebele',
        name: 'Ndebele',
        aka: 'amaNdebele',
        symbol: '🎨',
        image: 'Ndebele.jpg',
      },
      {
        id: 'bapedi',
        name: 'Bapedi',
        aka: 'baPedi',
        symbol: '⚔️',
        image: 'Bapedi.jpg',
      },
      // --- Added the three missing tribes ---
      {
        id: 'swati',
        name: 'Swati',
        aka: 'emaSwati',
        symbol: '🦁',
        image: 'swati.webp',
      },
      {
        id: 'xhosa',
        name: 'Xhosa',
        aka: 'amaXhosa',
        symbol: '🐃',
        image: 'xhosa.webp',
      },
      {
        id: 'boere',
        name: 'Boere',
        aka: 'Afrikaner',
        symbol: '🐏',
        image: 'boere.webp',
      },
    ],
  },
  // Other countries – unchanged
  {
    id: 'ng',
    name: 'Nigeria',
    code: 'NG',
    tagline: 'COMING SOON',
    available: false,
    guestAccessible: false,
    cultures: [],
  },
  {
    id: 'gh',
    name: 'Ghana',
    code: 'GH',
    tagline: 'COMING SOON',
    available: false,
    guestAccessible: false,
    cultures: [],
  },
  {
    id: 'ke',
    name: 'Kenya',
    code: 'KE',
    tagline: 'COMING SOON',
    available: false,
    guestAccessible: false,
    cultures: [],
  },
  {
    id: 'eg',
    name: 'Egypt',
    code: 'EG',
    tagline: 'COMING SOON',
    available: false,
    guestAccessible: false,
    cultures: [],
  },
  {
    id: 'et',
    name: 'Ethiopia',
    code: 'ET',
    tagline: 'COMING SOON',
    available: false,
    guestAccessible: false,
    cultures: [],
  },
];